module.exports = Object.freeze({
    PENDING: 'PENDING',
    PLACED: 'PLACED',
    ASSIGNED:'ASSIGNED',
    DISPATCHED: 'DISPATCHED',
    STARTED_OFF:'STARTED_OFF',
    COMPLETED:'COMPLETED',
    DELIVERED:'DELIVERED',
    CANCEL:'CANCEL',
    REASSIGNED:'REASSIGNED',
    UNDER_REVIEW:'UNDER_REVIEW',
})