const auth = require("../controllers/adminController");
const authJwt = require("../middlewares/authJwt");
const express = require("express");
const router = express()
const { cpUpload0, upload, upload1, upload2, cpUpload, bannerUpload, offerUpload, categoryUpload, subCategoryUpload } = require('../middlewares/imageUpload')
module.exports = (app) => {
        app.post("/api/v1/admin/registration", auth.registration);
        app.post("/api/v1/admin/login", auth.signin);
        app.get("/api/v1/admin/getProfile", [authJwt.verifyToken], auth.getProfile);
        app.put("/api/v1/admin/update", [authJwt.verifyToken], auth.update);
        app.get("/api/v1/admin/getAllUser", auth.getAllUser);
        app.get("/api/v1/admin/getAllVendor", auth.getAllVendor);
        app.put("/api/v1/admin/blockUnblockUser/:id", [authJwt.verifyToken], auth.blockUnblockUser);
        app.get("/api/v1/admin/viewUser/:id", [authJwt.verifyToken], auth.viewUser);
        app.delete("/api/v1/admin/:id", [authJwt.verifyToken], auth.deleteUser);
        app.post("/api/v1/Category/addCategory", [authJwt.verifyToken], subCategoryUpload.single('image'), auth.createCategory);
        app.get("/api/v1/Category/allCategory", auth.getCategories);
        app.get("/api/v1/Category/paginateCategoriesSearch", auth.paginateCategoriesSearch);
        app.put("/api/v1/Category/updateCategory/:id", [authJwt.verifyToken], subCategoryUpload.single('image'), auth.updateCategory);
        app.delete("/api/v1/Category/deleteCategory/:id", [authJwt.verifyToken], auth.removeCategory);
        app.put("/api/v1/Category/approvedRejectCategory/:id", [authJwt.verifyToken], auth.approvedRejectCategory);
        app.post("/api/v1/SubCategory/addSubcategory", [authJwt.verifyToken], subCategoryUpload.single('image'), auth.createSubCategory);
        app.get("/api/v1/SubCategory/:id", auth.getIdSubCategory);
        app.put("/api/v1/SubCategory/updateSubcategory/:id", [authJwt.verifyToken], subCategoryUpload.single('image'), auth.updateSubCategory);
        app.delete("/api/v1/SubCategory/deleteSubcategory/:id", [authJwt.verifyToken], auth.deleteSubCategory);
        app.get("/api/v1/SubCategory/all/Subcategory", auth.getSubCategory);
        app.get("/api/v1/SubCategory/all/SubCategoryForAdmin", auth.getSubCategoryForAdmin);
        app.get("/api/v1/SubCategory/paginate/SubCategoriesSearch", auth.paginateSubCategoriesSearch);
        app.get("/api/v1/SubCategory/allSubcategoryById/:categoryId", auth.getSubCategoryByCategoryId);
        app.get("/api/v1/admin/allTransactionUser", auth.allTransactionUser);
        app.get("/api/v1/admin/allcreditTransactionUser", auth.allcreditTransactionUser);
        app.get("/api/v1/admin/allDebitTransactionUser", auth.allDebitTransactionUser);
        app.get("/api/v1/admin/Orders", [authJwt.verifyToken], auth.getOrders);
        app.post("/api/v1/Banner/addBanner", [authJwt.verifyToken], bannerUpload.single('image'), auth.createBanner);
        app.get("/api/v1/Banner/getBanner", auth.getBanner);
        app.get("/api/v1/Banner/:id", auth.getIdBanner);
        app.delete("/api/v1/Banner/:id", [authJwt.verifyToken], auth.deleteBanner);
        app.put("/api/v1/Banner/updateBanner/:id", [authJwt.verifyToken], bannerUpload.single('image'), auth.updateBanner);
        app.post("/api/v1/help/addQuery", auth.addQuery);
        app.get("/api/v1/help/all", auth.getAllHelpandSupport);
        app.get("/api/v1/help/:id", auth.getHelpandSupportById);
        app.delete("/api/v1/help/:id", auth.deleteHelpandSupport);
        app.post("/api/v1/ContactDetails/addContactDetails", [authJwt.verifyToken], auth.addContactDetails);
        app.get("/api/v1/ContactDetails/viewContactDetails", auth.viewContactDetails);
        app.post("/api/v1/notification/sendNotification", authJwt.verifyToken, auth.sendNotification);
        app.get("/api/v1/notification/allNotification", authJwt.verifyToken, auth.allNotification);
        app.post("/api/v1/Coupan/addCoupan", [authJwt.verifyToken], auth.addCoupan);
        app.get("/api/v1/Coupan/listCoupan", [authJwt.verifyToken], auth.listCoupan);
        app.delete("/api/v1/Coupan/:id", [authJwt.verifyToken], auth.deleteCoupan);
        app.put("/api/v1/kyc/vendorKycVerification", [authJwt.verifyToken], auth.vendorKycVerification);
        app.put("/api/v1/kyc/vendorKybVerification", [authJwt.verifyToken], auth.vendorKybVerification);
        app.get("/api/v1/admin/KycList", [authJwt.verifyToken], auth.KycList);
        app.get("/api/v1/admin/KybList", [authJwt.verifyToken], auth.KybList);
        app.get("/api/v1/getIdvendorKyb/:id", auth.getIdvendorKyb);
        app.get('/api/v1/admin/Product/list', auth.listProduct);
        app.delete('/api/v1/admin/Product/delete/:id', authJwt.verifyToken, auth.deleteProduct);
        app.get('/api/v1/admin/listProductVarient', auth.listProductVarient);
        app.get('/api/v1/admin/dashboard', auth.dashboard);
        app.get("/api/v1/admin/getcancelReturnOrder", [authJwt.verifyToken], auth.getcancelReturnOrder);
        app.put("/api/v1/admin/acceptRejectCancelReturnOrder/:id", [authJwt.verifyToken], auth.acceptRejectCancelReturnOrder);
        app.post("/api/v1/admin/Offer/addOffer", [authJwt.verifyToken], offerUpload.single('image'), auth.addOffer);
        app.get("/api/v1/admin/Offer/listOffer", auth.listOffer);
        app.put("/api/v1/admin/refundPayment/:id", [authJwt.verifyToken], auth.refundPayment);
        app.get("/api/v1/admin/ticket/listTicket", [authJwt.verifyToken], auth.listTicket);
        app.put('/api/v1/admin/replyOnTicket/:id', [authJwt.verifyToken], auth.replyOnTicket);
        app.put('/api/v1/admin/closeTicket/:id', [authJwt.verifyToken], auth.closeTicket);
        app.post('/api/v1/admin/addCodTovendor', [authJwt.verifyToken], auth.addCodTovendor);
        app.put('/api/v1/admin/updateCodTovendor/:id', [authJwt.verifyToken], auth.editCodTovendor);
        app.get("/api/v1/admin/listCod", [authJwt.verifyToken], auth.listCod);
        app.post("/api/v1/admin/Brand/addBrand", [authJwt.verifyToken], upload.single('image'), auth.createBrands);
        app.get("/api/v1/admin/Brand/allBrand", auth.getBrands);
        app.put("/api/v1/admin/Brand/updateBrand/:id", [authJwt.verifyToken], upload.single('image'), auth.updateBrand);
        app.delete("/api/v1/admin/Brand/deleteBrand/:id", [authJwt.verifyToken], auth.removeBrand);
}