const auth = require("../controllers/userController");
const authJwt = require("../middlewares/authJwt");
const { cpUpload0, upload, upload1, upload2, cpUpload, categoryUpload, subCategoryUpload } = require("../middlewares/imageUpload")
const express = require("express");
const router = express()
module.exports = (app) => {
        app.post("/api/v1/user/forgetPassword", auth.forgetPassword);
        app.post("/api/v1/user/changePassword", auth.changePassword);
        app.get("/api/v1/user/allCategory/:gender", auth.getCategories);
        app.get("/api/v1/user/allSubcategoryById/:categoryId", auth.getSubCategoryByCategoryId);
        app.get("/api/v1/user/Product/list", auth.listProduct);
        app.post("/api/v1/product/createProductReview", authJwt.verifyToken, auth.createProductReview);
        app.get("/api/v1/product/getProductReviews/:id", auth.getProductReviews);
        app.get("/api/v1/user/listProductVarient", auth.listProductVarient);
        app.post("/api/v1/cart/addtocart", authJwt.verifyToken, auth.addtocart);
        app.get("/api/v1/cart/getCart", authJwt.verifyToken, auth.getCart);
        app.delete("/api/v1/cart/deleteCart", authJwt.verifyToken, auth.deleteCart);
        app.put("/api/v1/cart/deletecartItem/:id", authJwt.verifyToken, auth.deletecartItem);
        app.put("/api/v1/cart/addAdressToCart", [authJwt.verifyToken], auth.addAdressToCart);
        app.put("/api/v1/user/updateQuantity", [authJwt.verifyToken], auth.updateQuantity);
        app.put("/api/v1/cart/changePaymentOption", [authJwt.verifyToken], auth.changePaymentOption);
        app.post("/api/v1/cart/checkout", authJwt.verifyToken, auth.checkout);
        app.post("/api/v1/cart/placeOrder/:orderId", [authJwt.verifyToken], auth.placeOrder);
        app.get("/api/v1/cart/successOrder/:orderId", [authJwt.verifyToken], auth.successOrder);
        app.get("/api/v1/cart/successOrderwithWallet/:orderId", [authJwt.verifyToken], auth.successOrderwithWallet);
        app.get("/api/v1/cart/cancelOrder/:orderId", [authJwt.verifyToken], auth.cancelOrder);
        app.put("/api/v1/order/cancelReturnOrder/:id", [authJwt.verifyToken], auth.cancelReturnOrder);
        app.get("/api/v1/order/getcancelReturnOrder", [authJwt.verifyToken], auth.getcancelReturnOrder);
        app.get("/api/v1/order/allOrders", [authJwt.verifyToken], auth.getAllOrders);
        app.get("/api/v1/order/Orders", [authJwt.verifyToken], auth.getOrders);
        app.get("/api/v1/order/viewOrder/:id", [authJwt.verifyToken], auth.getOrderbyId);
        app.get("/api/v1/transaction/allTransactionUser", [authJwt.verifyToken], auth.allTransactionUser);
        app.get("/api/v1/transaction/allcreditTransactionUser", [authJwt.verifyToken], auth.allcreditTransactionUser);
        app.get("/api/v1/transaction/allDebitTransactionUser", [authJwt.verifyToken], auth.allDebitTransactionUser);
        app.post("/api/v1/wallet/addWallet", [authJwt.verifyToken], auth.addMoney);
        app.get("/api/v1/wallet/getwallet", [authJwt.verifyToken], auth.getWallet);
        app.post("/api/v1/wallet/sendMoney", [authJwt.verifyToken], auth.sendMoney);
        app.post("/api/v1/user/createWishlist/:id", [authJwt.verifyToken], auth.createWishlist);
        app.post("/api/v1/user/removeFromWishlist/:id", [authJwt.verifyToken], auth.removeFromWishlist);
        app.get("/api/v1/user/myWishlist", [authJwt.verifyToken], auth.myWishlist);
        app.post("/api/v1/user/ticket/createTicket", [authJwt.verifyToken], auth.createTicket);
        app.get("/api/v1/user/ticket/listTicket", [authJwt.verifyToken], auth.listTicket);
        app.get('/user/ticket/:id', auth.getTicketbyId);
        app.put('/user/replyOnTicket/:id', [authJwt.verifyToken], auth.replyOnTicket);
        app.get("/api/v1/user/product/getMostDemandedProducts", auth.getMostDemandedProducts);
        app.get("/api/v1/user/product/getNewArrivalProducts", auth.getNewArrivalProducts);
        app.put('/user/updateNotifactionStatus', [authJwt.verifyToken], auth.updateNotifactionStatus);
        app.put('/user/updatePopup', [authJwt.verifyToken], auth.updatePopup);
        app.put('/user/updateOrderHistory', [authJwt.verifyToken], auth.updateOrderHistory);
}
// module.exports = router;