const auth = require("../controllers/vendorController");
const user = require("../controllers/userController");
const authJwt = require("../middlewares/authJwt");
const { cpUpload0, upload, upload1, upload2, cpUpload, kpUpload, categoryUpload, offerUpload, subCategoryUpload } = require('../middlewares/imageUpload')
const express = require("express");
const router = express()
module.exports = (app) => {
        app.post("/api/v1/vendor/registration", auth.registration);
        app.post("/api/v1/vendor/loginwithphone", auth.loginwithphone);
        app.post("/api/v1/vendor/:id", auth.verifyOtp);
        app.post("/api/v1/vendor/resendOtp/:id", auth.resendOTP);
        app.get("/api/v1/vendor/getProfile", authJwt.verifyToken, auth.getProfile);
        app.put("/api/v1/vendor/updateProfile", authJwt.verifyToken, upload.single('image'), auth.update);
        app.post("/api/v1/vendor/social/Login", auth.socialLogin);
        app.post("/api/v1/vendor/forgetPassword", auth.forgetPassword);
        app.post("/api/v1/vendor/resetPassword", auth.resetPassword);
        app.post("/api/v1/vendor/login/withPassword", auth.signin);
        app.post('/api/v1/vendor/QuantityUnit/add', authJwt.verifyToken, auth.addQuantityUnit);
        app.get("/api/v1/vendor/QuantityUnit/view/:id", auth.viewQuantityUnit);
        app.put('/api/v1/vendor/QuantityUnit/edit/:id', authJwt.verifyToken, auth.editQuantityUnit);
        app.delete('/api/v1/vendor/QuantityUnit/delete/:id', authJwt.verifyToken, auth.deleteQuantityUnit);
        app.get('/api/v1/vendor/QuantityUnit/list', authJwt.verifyToken, auth.listQuantityUnit);
        app.post('/api/v1/vendor/Color/add', authJwt.verifyToken, auth.addColor);
        app.get("/api/v1/vendor/Color/view/:id", auth.viewColor);
        app.put('/api/v1/vendor/Color/edit/:id', authJwt.verifyToken, auth.editColor);
        app.delete('/api/v1/vendor/Color/delete/:id', authJwt.verifyToken, auth.deleteColor);
        app.get('/api/v1/vendor/Color/list', authJwt.verifyToken, auth.listColor);
        app.post('/api/v1/vendor/Product/add', authJwt.verifyToken, upload.array('image'), auth.addProduct);
        app.get('/api/v1/vendor/Product/view/:id', auth.viewProduct);
        app.get('/api/v1/vendor/Product/list', authJwt.verifyToken, auth.listProduct);
        app.put('/api/v1/vendor/Product/edit/:id', authJwt.verifyToken, upload.array('image'), auth.editProduct);
        app.delete('/api/v1/vendor/Product/delete/:id', authJwt.verifyToken, auth.deleteProduct);
        app.post('/api/v1/vendor/ProductVarient/add', authJwt.verifyToken, auth.addProductVarient);
        app.get('/api/v1/vendor/ProductVarient/view/:id', auth.viewProductVarient);
        app.put('/api/v1/vendor/ProductVarient/edit/:id', authJwt.verifyToken, auth.editProductVarient);
        app.put('/api/v1/vendor/ProductVarient/uploadImage/:id', authJwt.verifyToken, upload.array('image'), auth.uploadImageInVarient);
        app.delete('/api/v1/vendor/ProductVarient/delete/:id', authJwt.verifyToken, auth.deleteProductVarient);
        app.get('/api/v1/vendor/ProductVarient/list', authJwt.verifyToken, auth.listProductVarient);
        app.post('/api/v1/vendor/ProductColor/add', authJwt.verifyToken, upload.array('image'), auth.addColorInProduct);
        app.put('/api/v1/vendor/ProductColor/edit/:id', authJwt.verifyToken, upload.array('image'), auth.editColorInProduct);
        app.post('/api/v1/vendor/VarientInColor/add', authJwt.verifyToken, auth.addVarientInColor);
        app.put('/api/v1/vendor/VarientInColor/edit/:id', authJwt.verifyToken, auth.editVarientInColor);
        app.delete('/api/v1/vendor/VarientInColor/delete/:id', authJwt.verifyToken, auth.deleteVarientInColor);
        app.delete('/api/v1/vendor/VarientInColor/deleteImage/:id', authJwt.verifyToken, auth.deleteImagefromVarient);
        app.get("/api/v1/vendor/Orders", [authJwt.verifyToken], auth.getOrders);
        app.post("/api/v1/kyc/addKYC", [authJwt.verifyToken], cpUpload, auth.addKYC);
        app.get("/api/v1/kyc/KycList", [authJwt.verifyToken], auth.KycList);
        app.post("/api/v1/kyc/addKYB", [authJwt.verifyToken], kpUpload, auth.addKYB);
        app.get("/api/v1/kyc/KybList", [authJwt.verifyToken], auth.KybList);
        app.get("/api/v1/vendor/getcancelReturnOrder", [authJwt.verifyToken], auth.getcancelReturnOrder);
        app.post("/api/v1/vendor/Offer/addOffer", [authJwt.verifyToken], offerUpload.single('image'), auth.addOffer);
        app.get("/api/v1/vendor/Offer/listOffer", [authJwt.verifyToken], auth.listOffer);
        app.get('/api/v1/vendor/dashboard', [authJwt.verifyToken], auth.dashboard);
        app.put("/api/v1/order/changeOrderStatus/:id", [authJwt.verifyToken], auth.changeOrderStatus);
}
// module.exports = router;